
# need to make sure that the root folder takes Wildfires as a root

program:  # These are the arguments that define how the train.py script works
  seed: 0
  output_dir: output
  data_dir: data
  log_dir: logs
  overwrite: False
  # conda_env: cuda11
  # notification_email: ss2536@cam.ac.uk
  

trainer:
  gpus: 1
  min_epochs: 1
  max_epochs: 5
  # benchmark: True
  
module:
    segmentation_model: "fcn"
    in_channels: 10
    num_classes: 6
    num_filters: 64
    loss: "ce"
    learning_rate: 1e-2
    learning_rate_schedule_patience: 6
    ignore_zeros: False
    
datamodule:
    root_dir: "src/datamodules/landcover"
    modis_root_dir: "data/MODIS/*/"
    landcover_root_dir: "data/Classified/"
    batch_size: 32
    num_workers: 1